FROM anapsix/alpine-java
MAINTAINER andreea oncea
COPY TransportantionCompany-0.0.1-SNAPSHOT.jar /opt/spring-cloud/lib/
CMD ["java", "-jar", "/opt/spring-cloud/lib/TransportantionCompany-0.0.1-SNAPSHOT.jar"]
EXPOSE 8081